'use strict';
Object.defineProperty(exports, '__esModule', { value: true });
var index = require('../src/index');
var chai_1 = require('chai');
describe('index', function () {
  it('should export Observable', function () {
    chai_1.expect(index.Observable).to.exist;
    chai_1.expect(index.ConnectableObservable).to.exist;
    var operator;
  });
  it('should export the Subject types', function () {
    chai_1.expect(index.Subject).to.exist;
    chai_1.expect(index.BehaviorSubject).to.exist;
    chai_1.expect(index.ReplaySubject).to.exist;
    chai_1.expect(index.AsyncSubject).to.exist;
  });
  it('should export the schedulers', function () {
    chai_1.expect(index.asapScheduler).to.exist;
    chai_1.expect(index.asyncScheduler).to.exist;
    chai_1.expect(index.queueScheduler).to.exist;
    chai_1.expect(index.animationFrameScheduler).to.exist;
    chai_1.expect(index.VirtualTimeScheduler).to.exist;
    chai_1.expect(index.VirtualAction).to.exist;
  });
  it('should export Subscription', function () {
    chai_1.expect(index.Subscription).to.exist;
    chai_1.expect(index.Subscriber).to.exist;
  });
  it('should export Notification', function () {
    chai_1.expect(index.Notification).to.exist;
  });
  it('should export the appropriate utilities', function () {
    chai_1.expect(index.pipe).to.exist;
    chai_1.expect(index.noop).to.exist;
    chai_1.expect(index.identity).to.exist;
  });
  it('should export error types', function () {
    chai_1.expect(index.ArgumentOutOfRangeError).to.exist;
    chai_1.expect(index.EmptyError).to.exist;
    chai_1.expect(index.ObjectUnsubscribedError).to.exist;
    chai_1.expect(index.UnsubscriptionError).to.exist;
    chai_1.expect(index.TimeoutError).to.exist;
  });
  it('should export constants', function () {
    chai_1.expect(index.EMPTY).to.exist;
    chai_1.expect(index.NEVER).to.exist;
  });
  it('should export static observable creator functions', function () {
    chai_1.expect(index.bindCallback).to.exist;
    chai_1.expect(index.bindNodeCallback).to.exist;
    chai_1.expect(index.combineLatest).to.exist;
    chai_1.expect(index.concat).to.exist;
    chai_1.expect(index.defer).to.exist;
    chai_1.expect(index.empty).to.exist;
    chai_1.expect(index.forkJoin).to.exist;
    chai_1.expect(index.from).to.exist;
    chai_1.expect(index.fromEvent).to.exist;
    chai_1.expect(index.fromEventPattern).to.exist;
    chai_1.expect(index.generate).to.exist;
    chai_1.expect(index.iif).to.exist;
    chai_1.expect(index.interval).to.exist;
    chai_1.expect(index.merge).to.exist;
    chai_1.expect(index.of).to.exist;
    chai_1.expect(index.onErrorResumeNext).to.exist;
    chai_1.expect(index.pairs).to.exist;
    chai_1.expect(index.race).to.exist;
    chai_1.expect(index.range).to.exist;
    chai_1.expect(index.throwError).to.exist;
    chai_1.expect(index.timer).to.exist;
    chai_1.expect(index.using).to.exist;
    chai_1.expect(index.zip).to.exist;
  });
  it('should export all of the operators', function () {
    chai_1.expect(index.audit).to.exist;
    chai_1.expect(index.auditTime).to.exist;
    chai_1.expect(index.buffer).to.exist;
    chai_1.expect(index.bufferCount).to.exist;
    chai_1.expect(index.bufferTime).to.exist;
    chai_1.expect(index.bufferToggle).to.exist;
    chai_1.expect(index.bufferWhen).to.exist;
    chai_1.expect(index.catchError).to.exist;
    chai_1.expect(index.combineAll).to.exist;
    chai_1.expect(index.combineLatestAll).to.exist;
    chai_1.expect(index.combineLatestWith).to.exist;
    chai_1.expect(index.concatAll).to.exist;
    chai_1.expect(index.concatMap).to.exist;
    chai_1.expect(index.concatMapTo).to.exist;
    chai_1.expect(index.concatWith).to.exist;
    chai_1.expect(index.connect).to.exist;
    chai_1.expect(index.count).to.exist;
    chai_1.expect(index.debounce).to.exist;
    chai_1.expect(index.debounceTime).to.exist;
    chai_1.expect(index.defaultIfEmpty).to.exist;
    chai_1.expect(index.delay).to.exist;
    chai_1.expect(index.delayWhen).to.exist;
    chai_1.expect(index.dematerialize).to.exist;
    chai_1.expect(index.distinct).to.exist;
    chai_1.expect(index.distinctUntilChanged).to.exist;
    chai_1.expect(index.distinctUntilKeyChanged).to.exist;
    chai_1.expect(index.elementAt).to.exist;
    chai_1.expect(index.endWith).to.exist;
    chai_1.expect(index.every).to.exist;
    chai_1.expect(index.exhaust).to.exist;
    chai_1.expect(index.exhaustAll).to.exist;
    chai_1.expect(index.exhaustMap).to.exist;
    chai_1.expect(index.expand).to.exist;
    chai_1.expect(index.filter).to.exist;
    chai_1.expect(index.finalize).to.exist;
    chai_1.expect(index.find).to.exist;
    chai_1.expect(index.findIndex).to.exist;
    chai_1.expect(index.first).to.exist;
    chai_1.expect(index.groupBy).to.exist;
    chai_1.expect(index.ignoreElements).to.exist;
    chai_1.expect(index.isEmpty).to.exist;
    chai_1.expect(index.last).to.exist;
    chai_1.expect(index.map).to.exist;
    chai_1.expect(index.mapTo).to.exist;
    chai_1.expect(index.materialize).to.exist;
    chai_1.expect(index.max).to.exist;
    chai_1.expect(index.mergeAll).to.exist;
    chai_1.expect(index.flatMap).to.exist;
    chai_1.expect(index.mergeMap).to.exist;
    chai_1.expect(index.mergeMapTo).to.exist;
    chai_1.expect(index.mergeScan).to.exist;
    chai_1.expect(index.mergeWith).to.exist;
    chai_1.expect(index.min).to.exist;
    chai_1.expect(index.multicast).to.exist;
    chai_1.expect(index.observeOn).to.exist;
    chai_1.expect(index.pairwise).to.exist;
    chai_1.expect(index.pluck).to.exist;
    chai_1.expect(index.publish).to.exist;
    chai_1.expect(index.publishBehavior).to.exist;
    chai_1.expect(index.publishLast).to.exist;
    chai_1.expect(index.publishReplay).to.exist;
    chai_1.expect(index.raceWith).to.exist;
    chai_1.expect(index.reduce).to.exist;
    chai_1.expect(index.repeat).to.exist;
    chai_1.expect(index.repeatWhen).to.exist;
    chai_1.expect(index.retry).to.exist;
    chai_1.expect(index.retryWhen).to.exist;
    chai_1.expect(index.refCount).to.exist;
    chai_1.expect(index.sample).to.exist;
    chai_1.expect(index.sampleTime).to.exist;
    chai_1.expect(index.scan).to.exist;
    chai_1.expect(index.sequenceEqual).to.exist;
    chai_1.expect(index.share).to.exist;
    chai_1.expect(index.shareReplay).to.exist;
    chai_1.expect(index.single).to.exist;
    chai_1.expect(index.skip).to.exist;
    chai_1.expect(index.skipLast).to.exist;
    chai_1.expect(index.skipUntil).to.exist;
    chai_1.expect(index.skipWhile).to.exist;
    chai_1.expect(index.startWith).to.exist;
    chai_1.expect(index.subscribeOn).to.exist;
    chai_1.expect(index.switchAll).to.exist;
    chai_1.expect(index.switchMap).to.exist;
    chai_1.expect(index.switchMapTo).to.exist;
    chai_1.expect(index.switchScan).to.exist;
    chai_1.expect(index.take).to.exist;
    chai_1.expect(index.takeLast).to.exist;
    chai_1.expect(index.takeUntil).to.exist;
    chai_1.expect(index.takeWhile).to.exist;
    chai_1.expect(index.tap).to.exist;
    chai_1.expect(index.throttle).to.exist;
    chai_1.expect(index.throttleTime).to.exist;
    chai_1.expect(index.throwIfEmpty).to.exist;
    chai_1.expect(index.timeInterval).to.exist;
    chai_1.expect(index.timeout).to.exist;
    chai_1.expect(index.timeoutWith).to.exist;
    chai_1.expect(index.timestamp).to.exist;
    chai_1.expect(index.toArray).to.exist;
    chai_1.expect(index.window).to.exist;
    chai_1.expect(index.windowCount).to.exist;
    chai_1.expect(index.windowTime).to.exist;
    chai_1.expect(index.windowToggle).to.exist;
    chai_1.expect(index.windowWhen).to.exist;
    chai_1.expect(index.withLatestFrom).to.exist;
    chai_1.expect(index.zipAll).to.exist;
    chai_1.expect(index.zipWith).to.exist;
  });
  it('should expose configuration', function () {
    chai_1.expect(index.config).to.exist;
  });
});
//# sourceMappingURL=index-spec.js.map
